### ISSUE TITLE
Issues on latest IOS

### ISSUE THREAD

**Issue by NathanaelA** [mcgouganp/nativescript-sha#2]
[x] Make sure to check the demo app(s) for sample usage 
[x] Make sure to check the existing issues in this repository 

### Which platform(s) does your issue occur on?
iOS

### Please, provide the following version numbers that your issue occurs with:
6.2 & 6.3

---

Issue is that the string returned from iOS NSData.toString is based on the description value which apparently changed is in iOS 13?

On line https://github.com/mcgouganp/nativescript-sha/blob/master/src/sha.ios.ts#L10
returns a string with the length and other description information and so it looks like this.
`{length=32,bytes=0x53467759aba42ff3a9aab426736364bd...2a49cdb0748588d1}`

So I replaced that line with this code - (not sure this is the best version to fix the code, but it is reliable on all versions of iOS and shouldn't fail in the future...  :grinning: );
```
    // Convert the iOS NSData to a JavaScript ArrayBuffer
    let buffer = interop.bufferFromData(sha256);

    // Grab a UINT view on the Buffer
    let view = new Uint8Array(buffer);

    // Simple for/i loop to loop over the 32 elements.
    let rstring = "";
    for (let i = 0; i < 32; i++) {
        rstring += intToHex(view[i]);
    }

    return rstring;
```

Add this function, it basically will make sure all HEX values returned are at least two digits wide
This will match what android will generate including casing of the hex values.
```
function intToHex(i) {
    let r =  i.toString(16);
    if (r.length === 1) { return "0" + r; }
    return r;
}
```

**Comment by mcgouganp** [comment]
Thanks for spotting this.
I've made this fix, added some more algorithms and released v1.0.2.
